### ISSUE TITLE
pythonwhat can't parse a comment with the phrase "encoding: target"

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#197]
¯\\\_(ツ)\_/¯

Parsing a comment of the form below is bad.

```
# encoding: target
```

Parsing code of the form below here is okay.

```
encoding = [1, 2]
target = 1

for ii in encoding: target + 1
```

**Original stacktrace below.**

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/tokenize.py", line 404, in find_cookie
    codec = lookup(encoding)
LookupError: unknown encoding: target

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/python/site-packages/pythonwhat/State.py", line 266, in parse_int
    utils_ast.mark_text_ranges(res, x + '\n')
  File "/var/lib/python/site-packages/pythonwhat/utils_ast.py", line 301, in mark_text_ranges
    all_tokens = list(tokenize.tokenize(io.BytesIO(source.encode('utf-8')).readline))
  File "/usr/lib/python3.5/tokenize.py", line 488, in tokenize
    encoding, consumed = detect_encoding(readline)
  File "/usr/lib/python3.5/tokenize.py", line 433, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/lib/python3.5/tokenize.py", line 412, in find_cookie
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: unknown encoding: target

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/python/site-packages/pythonbackend/commands.py", line 34, in submit
    output.extend(Exercise.active_exercise.runSubmit(json.loads(json_data)))
  File "/var/lib/python/site-packages/pythonbackend/Exercise.py", line 103, in runSubmit
    raw_output["error"]
  File "/var/lib/python/site-packages/pythonwhat/test_exercise.py", line 59, in test_exercise
    raw_student_output = check_str(raw_student_output))
  File "/var/lib/python/site-packages/pythonwhat/State.py", line 94, in __init__
    self.solution_tree = State.parse_int(self.solution_code)
  File "/var/lib/python/site-packages/pythonwhat/State.py", line 269, in parse_int
    raise SyntaxError(str(e))
  File "<string>", line None
SyntaxError: unknown encoding: target
```

taken from https://github.com/datacamp/campus-app/issues/589

**Comment by machow** [comment]
Just a note, this is likely due to some tokenization done when trying to pull line info from AST representations. No idea why--and it would likely take a good chunk of time to figure it out...

**Comment by filipsch** [comment]
@machow this is awesome! Thanks! Bye bye thonny!

**Comment by filipsch** [comment]
Switcheroo to `asttoken` has been done on a branch; just have to remove the hacky parts, battle test it, and deploy it.
